version: "3.8"

services:
  wazuh-deployment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wazuh-deployment
    restart: unless-stopped
    ports:
      - "8080:8080" # API port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker socket
      - ./wazuh_data:/app/wazuh_data # Persistent data volume
    environment:
      - WAZUH_ADMIN_PASSWORD=AdminPa$w0rd2025
      - BASE_PORT=55000
      - DATA_DIR=/app/wazuh_data
      - DOCKER_WAZUH_IMAGE=wazuh/wazuh-manager:4.5.4 # Use a more stable version
    networks:
      - wazuh-network

networks:
  wazuh-network:
    name: wazuh-network
    driver: bridge
