# Generated by Django 5.1.6 on 2025-03-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='port',
            field=models.IntegerField(default=5601, max_length=5),
            preserve_default=False,
        ),
    ]
